name: Pull Request Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laboratory_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Nx set shas
        uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: npm i

      - name: Lint affected
        run: npx nx affected -t lint --parallel=3

      - name: Test affected
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build affected
        run: npx nx affected -t build --parallel=3

      - name: Build storybook affected
        run: npx nx affected -t build-storybook --parallel=3 --configuration=ci
